### ISSUE TITLE
exit status, int instead of string

### ISSUE THREAD

**Issue by Busedame** [alx-sch/42_minishell#69]
🌈 minishell$ expr $? + $?
expanded input: expr 0 + 0
expr: non-integer argument
Position[0]: 'expr' (token type: 5)
Position[5]: '$?' (token type: 5)
Position[8]: '+' (token type: 5)
Position[10]: '$?' (token type: 5)
🌈 minishell$ expr 5 + 5
expanded input: expr 5 + 5
10

The extension $? should be stored as an int instead of as a string.

**Comment by alx-sch** [comment]
Oh! That's bc there is no variable expansion yet (other than in heredocs).
Will fix this!
