### ISSUE TITLE
absolute paths for heredocs

### ISSUE THREAD

**Issue by alx-sch** [alx-sch/42_minishell#92]

**Comment by Busedame** [comment]
🌈 minishell$ << EOF << EOF2 | <<EOF3 | <<EOF4 ls -l
> dsajdsaj
> EOF
> dsad
> EOF2
> asjdjsdj
> EOF3
> dsadasd
> EOF4
ERROR: Failed to delete heredoc file: No such file or directory
minishell: .heredoc_2: No such file or directory
🌈 minishell$ << EOF << EOF2 | <<EOF3 | <<EOF4 ls -l
> dsad
> EOF
> dasjdsja
> EOF2
> djsdjaa
> EOF3
> fjsadjdjas
> dssdaj
> dsad
> EOF4
minishell: .heredoc_1: No such file or directory
total 188
drwxr-xr-x  2 nholbroo 2023_berlin   4096 Aug 12 19:26 include
drwxr-xr-x  3 nholbroo 2023_berlin   4096 Aug 12 19:30 libft
-rw-r--r--  1 nholbroo 2023_berlin   1068 Aug 12 15:00 LICENSE
-rw-r--r--  1 nholbroo 2023_berlin  10594 Aug 12 19:01 Makefile
-rwxr-xr-x  1 nholbroo 2023_berlin 161480 Aug 12 19:30 minishell_test
drwxr-xr-x 11 nholbroo 2023_berlin    181 Aug 12 19:30 obj
-rw-r--r--  1 nholbroo 2023_berlin   1058 Aug 12 15:00 README.md
drwxr-xr-x 11 nholbroo 2023_berlin    176 Aug 12 15:00 src
drwxr-xr-x 11 nholbroo 2023_berlin    181 Aug 12 19:26 src_test
🌈 minishell$
